#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyen_Asp.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Web_Truyen")]
	public partial class dbWeb_TruyenDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBinhLuan(BinhLuan instance);
    partial void UpdateBinhLuan(BinhLuan instance);
    partial void DeleteBinhLuan(BinhLuan instance);
    partial void InsertTRUYEN(TRUYEN instance);
    partial void UpdateTRUYEN(TRUYEN instance);
    partial void DeleteTRUYEN(TRUYEN instance);
    partial void InsertCAMXUC(CAMXUC instance);
    partial void UpdateCAMXUC(CAMXUC instance);
    partial void DeleteCAMXUC(CAMXUC instance);
    partial void InsertCHUONG(CHUONG instance);
    partial void UpdateCHUONG(CHUONG instance);
    partial void DeleteCHUONG(CHUONG instance);
    partial void InsertDANGNHAP(DANGNHAP instance);
    partial void UpdateDANGNHAP(DANGNHAP instance);
    partial void DeleteDANGNHAP(DANGNHAP instance);
    partial void InsertDECU(DECU instance);
    partial void UpdateDECU(DECU instance);
    partial void DeleteDECU(DECU instance);
    partial void InsertNHANTHUONG(NHANTHUONG instance);
    partial void UpdateNHANTHUONG(NHANTHUONG instance);
    partial void DeleteNHANTHUONG(NHANTHUONG instance);
    partial void InsertRank_DeCu(Rank_DeCu instance);
    partial void UpdateRank_DeCu(Rank_DeCu instance);
    partial void DeleteRank_DeCu(Rank_DeCu instance);
    partial void InsertReview(Review instance);
    partial void UpdateReview(Review instance);
    partial void DeleteReview(Review instance);
    partial void InsertTACGIA(TACGIA instance);
    partial void UpdateTACGIA(TACGIA instance);
    partial void DeleteTACGIA(TACGIA instance);
    partial void InsertTHELOAI(THELOAI instance);
    partial void UpdateTHELOAI(THELOAI instance);
    partial void DeleteTHELOAI(THELOAI instance);
    partial void InsertTHINHHANH(THINHHANH instance);
    partial void UpdateTHINHHANH(THINHHANH instance);
    partial void DeleteTHINHHANH(THINHHANH instance);
    partial void InsertTruyenDangDoc(TruyenDangDoc instance);
    partial void UpdateTruyenDangDoc(TruyenDangDoc instance);
    partial void DeleteTruyenDangDoc(TruyenDangDoc instance);
    #endregion
		
		public dbWeb_TruyenDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Web_TruyenConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbWeb_TruyenDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbWeb_TruyenDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbWeb_TruyenDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbWeb_TruyenDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<view_theloai> view_theloais
		{
			get
			{
				return this.GetTable<view_theloai>();
			}
		}
		
		public System.Data.Linq.Table<BinhLuan> BinhLuans
		{
			get
			{
				return this.GetTable<BinhLuan>();
			}
		}
		
		public System.Data.Linq.Table<TRUYEN> TRUYENs
		{
			get
			{
				return this.GetTable<TRUYEN>();
			}
		}
		
		public System.Data.Linq.Table<CAMXUC> CAMXUCs
		{
			get
			{
				return this.GetTable<CAMXUC>();
			}
		}
		
		public System.Data.Linq.Table<CHUONG> CHUONGs
		{
			get
			{
				return this.GetTable<CHUONG>();
			}
		}
		
		public System.Data.Linq.Table<DANGNHAP> DANGNHAPs
		{
			get
			{
				return this.GetTable<DANGNHAP>();
			}
		}
		
		public System.Data.Linq.Table<DECU> DECUs
		{
			get
			{
				return this.GetTable<DECU>();
			}
		}
		
		public System.Data.Linq.Table<NHANTHUONG> NHANTHUONGs
		{
			get
			{
				return this.GetTable<NHANTHUONG>();
			}
		}
		
		public System.Data.Linq.Table<Rank_DeCu> Rank_DeCus
		{
			get
			{
				return this.GetTable<Rank_DeCu>();
			}
		}
		
		public System.Data.Linq.Table<Review> Reviews
		{
			get
			{
				return this.GetTable<Review>();
			}
		}
		
		public System.Data.Linq.Table<TACGIA> TACGIAs
		{
			get
			{
				return this.GetTable<TACGIA>();
			}
		}
		
		public System.Data.Linq.Table<THELOAI> THELOAIs
		{
			get
			{
				return this.GetTable<THELOAI>();
			}
		}
		
		public System.Data.Linq.Table<THINHHANH> THINHHANHs
		{
			get
			{
				return this.GetTable<THINHHANH>();
			}
		}
		
		public System.Data.Linq.Table<TruyenDangDoc> TruyenDangDocs
		{
			get
			{
				return this.GetTable<TruyenDangDoc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_theloai")]
	public partial class view_theloai
	{
		
		private int _MaTruyen;
		
		private string _TenTruyen;
		
		private string _AnhBia;
		
		private string _TenTL;
		
		private string _MaTL;
		
		private string _TenTG;
		
		private string _TenFoder;
		
		private System.Nullable<int> _TongChuong;
		
		public view_theloai()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTruyen", DbType="Int NOT NULL")]
		public int MaTruyen
		{
			get
			{
				return this._MaTruyen;
			}
			set
			{
				if ((this._MaTruyen != value))
				{
					this._MaTruyen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTruyen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenTruyen
		{
			get
			{
				return this._TenTruyen;
			}
			set
			{
				if ((this._TenTruyen != value))
				{
					this._TenTruyen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhBia", DbType="VarChar(50)")]
		public string AnhBia
		{
			get
			{
				return this._AnhBia;
			}
			set
			{
				if ((this._AnhBia != value))
				{
					this._AnhBia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTL", DbType="NVarChar(50)")]
		public string TenTL
		{
			get
			{
				return this._TenTL;
			}
			set
			{
				if ((this._TenTL != value))
				{
					this._TenTL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTL", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string MaTL
		{
			get
			{
				return this._MaTL;
			}
			set
			{
				if ((this._MaTL != value))
				{
					this._MaTL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTG", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenTG
		{
			get
			{
				return this._TenTG;
			}
			set
			{
				if ((this._TenTG != value))
				{
					this._TenTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenFoder", DbType="VarChar(50)")]
		public string TenFoder
		{
			get
			{
				return this._TenFoder;
			}
			set
			{
				if ((this._TenFoder != value))
				{
					this._TenFoder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongChuong", DbType="Int")]
		public System.Nullable<int> TongChuong
		{
			get
			{
				return this._TongChuong;
			}
			set
			{
				if ((this._TongChuong != value))
				{
					this._TongChuong = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BinhLuan")]
	public partial class BinhLuan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBL;
		
		private System.Nullable<int> _MaTruyen;
		
		private System.Nullable<int> _MaDN;
		
		private string _NoiDung;
		
		private EntityRef<DANGNHAP> _DANGNHAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBLChanging(int value);
    partial void OnMaBLChanged();
    partial void OnMaTruyenChanging(System.Nullable<int> value);
    partial void OnMaTruyenChanged();
    partial void OnMaDNChanging(System.Nullable<int> value);
    partial void OnMaDNChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    #endregion
		
		public BinhLuan()
		{
			this._DANGNHAP = default(EntityRef<DANGNHAP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBL
		{
			get
			{
				return this._MaBL;
			}
			set
			{
				if ((this._MaBL != value))
				{
					this.OnMaBLChanging(value);
					this.SendPropertyChanging();
					this._MaBL = value;
					this.SendPropertyChanged("MaBL");
					this.OnMaBLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTruyen", DbType="Int")]
		public System.Nullable<int> MaTruyen
		{
			get
			{
				return this._MaTruyen;
			}
			set
			{
				if ((this._MaTruyen != value))
				{
					this.OnMaTruyenChanging(value);
					this.SendPropertyChanging();
					this._MaTruyen = value;
					this.SendPropertyChanged("MaTruyen");
					this.OnMaTruyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDN", DbType="Int")]
		public System.Nullable<int> MaDN
		{
			get
			{
				return this._MaDN;
			}
			set
			{
				if ((this._MaDN != value))
				{
					if (this._DANGNHAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDNChanging(value);
					this.SendPropertyChanging();
					this._MaDN = value;
					this.SendPropertyChanged("MaDN");
					this.OnMaDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(500)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANGNHAP_BinhLuan", Storage="_DANGNHAP", ThisKey="MaDN", OtherKey="MaDN", IsForeignKey=true)]
		public DANGNHAP DANGNHAP
		{
			get
			{
				return this._DANGNHAP.Entity;
			}
			set
			{
				DANGNHAP previousValue = this._DANGNHAP.Entity;
				if (((previousValue != value) 
							|| (this._DANGNHAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANGNHAP.Entity = null;
						previousValue.BinhLuans.Remove(this);
					}
					this._DANGNHAP.Entity = value;
					if ((value != null))
					{
						value.BinhLuans.Add(this);
						this._MaDN = value.MaDN;
					}
					else
					{
						this._MaDN = default(Nullable<int>);
					}
					this.SendPropertyChanged("DANGNHAP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRUYEN")]
	public partial class TRUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTruyen;
		
		private string _TenTruyen;
		
		private string _MaTG;
		
		private string _AnhBia;
		
		private string _TrangThai;
		
		private System.Nullable<int> _LuotXem;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private System.Nullable<int> _MaDN;
		
		private string _MaTL;
		
		private EntitySet<CAMXUC> _CAMXUCs;
		
		private EntitySet<CHUONG> _CHUONGs;
		
		private EntitySet<DECU> _DECUs;
		
		private EntitySet<NHANTHUONG> _NHANTHUONGs;
		
		private EntitySet<Rank_DeCu> _Rank_DeCus;
		
		private EntitySet<THINHHANH> _THINHHANHs;
		
		private EntitySet<TruyenDangDoc> _TruyenDangDocs;
		
		private EntityRef<DANGNHAP> _DANGNHAP;
		
		private EntityRef<TACGIA> _TACGIA;
		
		private EntityRef<THELOAI> _THELOAI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTruyenChanging(int value);
    partial void OnMaTruyenChanged();
    partial void OnTenTruyenChanging(string value);
    partial void OnTenTruyenChanged();
    partial void OnMaTGChanging(string value);
    partial void OnMaTGChanged();
    partial void OnAnhBiaChanging(string value);
    partial void OnAnhBiaChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnLuotXemChanging(System.Nullable<int> value);
    partial void OnLuotXemChanged();
    partial void OnNgayDangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangChanged();
    partial void OnMaDNChanging(System.Nullable<int> value);
    partial void OnMaDNChanged();
    partial void OnMaTLChanging(string value);
    partial void OnMaTLChanged();
    #endregion
		
		public TRUYEN()
		{
			this._CAMXUCs = new EntitySet<CAMXUC>(new Action<CAMXUC>(this.attach_CAMXUCs), new Action<CAMXUC>(this.detach_CAMXUCs));
			this._CHUONGs = new EntitySet<CHUONG>(new Action<CHUONG>(this.attach_CHUONGs), new Action<CHUONG>(this.detach_CHUONGs));
			this._DECUs = new EntitySet<DECU>(new Action<DECU>(this.attach_DECUs), new Action<DECU>(this.detach_DECUs));
			this._NHANTHUONGs = new EntitySet<NHANTHUONG>(new Action<NHANTHUONG>(this.attach_NHANTHUONGs), new Action<NHANTHUONG>(this.detach_NHANTHUONGs));
			this._Rank_DeCus = new EntitySet<Rank_DeCu>(new Action<Rank_DeCu>(this.attach_Rank_DeCus), new Action<Rank_DeCu>(this.detach_Rank_DeCus));
			this._THINHHANHs = new EntitySet<THINHHANH>(new Action<THINHHANH>(this.attach_THINHHANHs), new Action<THINHHANH>(this.detach_THINHHANHs));
			this._TruyenDangDocs = new EntitySet<TruyenDangDoc>(new Action<TruyenDangDoc>(this.attach_TruyenDangDocs), new Action<TruyenDangDoc>(this.detach_TruyenDangDocs));
			this._DANGNHAP = default(EntityRef<DANGNHAP>);
			this._TACGIA = default(EntityRef<TACGIA>);
			this._THELOAI = default(EntityRef<THELOAI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTruyen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTruyen
		{
			get
			{
				return this._MaTruyen;
			}
			set
			{
				if ((this._MaTruyen != value))
				{
					this.OnMaTruyenChanging(value);
					this.SendPropertyChanging();
					this._MaTruyen = value;
					this.SendPropertyChanged("MaTruyen");
					this.OnMaTruyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTruyen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenTruyen
		{
			get
			{
				return this._TenTruyen;
			}
			set
			{
				if ((this._TenTruyen != value))
				{
					this.OnTenTruyenChanging(value);
					this.SendPropertyChanging();
					this._TenTruyen = value;
					this.SendPropertyChanged("TenTruyen");
					this.OnTenTruyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="VarChar(10)")]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					if (this._TACGIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTGChanging(value);
					this.SendPropertyChanging();
					this._MaTG = value;
					this.SendPropertyChanged("MaTG");
					this.OnMaTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhBia", DbType="VarChar(50)")]
		public string AnhBia
		{
			get
			{
				return this._AnhBia;
			}
			set
			{
				if ((this._AnhBia != value))
				{
					this.OnAnhBiaChanging(value);
					this.SendPropertyChanging();
					this._AnhBia = value;
					this.SendPropertyChanged("AnhBia");
					this.OnAnhBiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(15)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotXem", DbType="Int")]
		public System.Nullable<int> LuotXem
		{
			get
			{
				return this._LuotXem;
			}
			set
			{
				if ((this._LuotXem != value))
				{
					this.OnLuotXemChanging(value);
					this.SendPropertyChanging();
					this._LuotXem = value;
					this.SendPropertyChanged("LuotXem");
					this.OnLuotXemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this.OnNgayDangChanging(value);
					this.SendPropertyChanging();
					this._NgayDang = value;
					this.SendPropertyChanged("NgayDang");
					this.OnNgayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDN", DbType="Int")]
		public System.Nullable<int> MaDN
		{
			get
			{
				return this._MaDN;
			}
			set
			{
				if ((this._MaDN != value))
				{
					if (this._DANGNHAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDNChanging(value);
					this.SendPropertyChanging();
					this._MaDN = value;
					this.SendPropertyChanged("MaDN");
					this.OnMaDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTL", DbType="NVarChar(5)")]
		public string MaTL
		{
			get
			{
				return this._MaTL;
			}
			set
			{
				if ((this._MaTL != value))
				{
					if (this._THELOAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTLChanging(value);
					this.SendPropertyChanging();
					this._MaTL = value;
					this.SendPropertyChanged("MaTL");
					this.OnMaTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRUYEN_CAMXUC", Storage="_CAMXUCs", ThisKey="MaTruyen", OtherKey="MaTruyen")]
		public EntitySet<CAMXUC> CAMXUCs
		{
			get
			{
				return this._CAMXUCs;
			}
			set
			{
				this._CAMXUCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRUYEN_CHUONG", Storage="_CHUONGs", ThisKey="MaTruyen", OtherKey="MaTruyen")]
		public EntitySet<CHUONG> CHUONGs
		{
			get
			{
				return this._CHUONGs;
			}
			set
			{
				this._CHUONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRUYEN_DECU", Storage="_DECUs", ThisKey="MaTruyen", OtherKey="MaTruyen")]
		public EntitySet<DECU> DECUs
		{
			get
			{
				return this._DECUs;
			}
			set
			{
				this._DECUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRUYEN_NHANTHUONG", Storage="_NHANTHUONGs", ThisKey="MaTruyen", OtherKey="MaTruyen")]
		public EntitySet<NHANTHUONG> NHANTHUONGs
		{
			get
			{
				return this._NHANTHUONGs;
			}
			set
			{
				this._NHANTHUONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRUYEN_Rank_DeCu", Storage="_Rank_DeCus", ThisKey="MaTruyen", OtherKey="MaTruyen")]
		public EntitySet<Rank_DeCu> Rank_DeCus
		{
			get
			{
				return this._Rank_DeCus;
			}
			set
			{
				this._Rank_DeCus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRUYEN_THINHHANH", Storage="_THINHHANHs", ThisKey="MaTruyen", OtherKey="MaTruyen")]
		public EntitySet<THINHHANH> THINHHANHs
		{
			get
			{
				return this._THINHHANHs;
			}
			set
			{
				this._THINHHANHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRUYEN_TruyenDangDoc", Storage="_TruyenDangDocs", ThisKey="MaTruyen", OtherKey="MaTruyen")]
		public EntitySet<TruyenDangDoc> TruyenDangDocs
		{
			get
			{
				return this._TruyenDangDocs;
			}
			set
			{
				this._TruyenDangDocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANGNHAP_TRUYEN", Storage="_DANGNHAP", ThisKey="MaDN", OtherKey="MaDN", IsForeignKey=true)]
		public DANGNHAP DANGNHAP
		{
			get
			{
				return this._DANGNHAP.Entity;
			}
			set
			{
				DANGNHAP previousValue = this._DANGNHAP.Entity;
				if (((previousValue != value) 
							|| (this._DANGNHAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANGNHAP.Entity = null;
						previousValue.TRUYENs.Remove(this);
					}
					this._DANGNHAP.Entity = value;
					if ((value != null))
					{
						value.TRUYENs.Add(this);
						this._MaDN = value.MaDN;
					}
					else
					{
						this._MaDN = default(Nullable<int>);
					}
					this.SendPropertyChanged("DANGNHAP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TACGIA_TRUYEN", Storage="_TACGIA", ThisKey="MaTG", OtherKey="MaTG", IsForeignKey=true)]
		public TACGIA TACGIA
		{
			get
			{
				return this._TACGIA.Entity;
			}
			set
			{
				TACGIA previousValue = this._TACGIA.Entity;
				if (((previousValue != value) 
							|| (this._TACGIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TACGIA.Entity = null;
						previousValue.TRUYENs.Remove(this);
					}
					this._TACGIA.Entity = value;
					if ((value != null))
					{
						value.TRUYENs.Add(this);
						this._MaTG = value.MaTG;
					}
					else
					{
						this._MaTG = default(string);
					}
					this.SendPropertyChanged("TACGIA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THELOAI_TRUYEN", Storage="_THELOAI", ThisKey="MaTL", OtherKey="MaTL", IsForeignKey=true)]
		public THELOAI THELOAI
		{
			get
			{
				return this._THELOAI.Entity;
			}
			set
			{
				THELOAI previousValue = this._THELOAI.Entity;
				if (((previousValue != value) 
							|| (this._THELOAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THELOAI.Entity = null;
						previousValue.TRUYENs.Remove(this);
					}
					this._THELOAI.Entity = value;
					if ((value != null))
					{
						value.TRUYENs.Add(this);
						this._MaTL = value.MaTL;
					}
					else
					{
						this._MaTL = default(string);
					}
					this.SendPropertyChanged("THELOAI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CAMXUCs(CAMXUC entity)
		{
			this.SendPropertyChanging();
			entity.TRUYEN = this;
		}
		
		private void detach_CAMXUCs(CAMXUC entity)
		{
			this.SendPropertyChanging();
			entity.TRUYEN = null;
		}
		
		private void attach_CHUONGs(CHUONG entity)
		{
			this.SendPropertyChanging();
			entity.TRUYEN = this;
		}
		
		private void detach_CHUONGs(CHUONG entity)
		{
			this.SendPropertyChanging();
			entity.TRUYEN = null;
		}
		
		private void attach_DECUs(DECU entity)
		{
			this.SendPropertyChanging();
			entity.TRUYEN = this;
		}
		
		private void detach_DECUs(DECU entity)
		{
			this.SendPropertyChanging();
			entity.TRUYEN = null;
		}
		
		private void attach_NHANTHUONGs(NHANTHUONG entity)
		{
			this.SendPropertyChanging();
			entity.TRUYEN = this;
		}
		
		private void detach_NHANTHUONGs(NHANTHUONG entity)
		{
			this.SendPropertyChanging();
			entity.TRUYEN = null;
		}
		
		private void attach_Rank_DeCus(Rank_DeCu entity)
		{
			this.SendPropertyChanging();
			entity.TRUYEN = this;
		}
		
		private void detach_Rank_DeCus(Rank_DeCu entity)
		{
			this.SendPropertyChanging();
			entity.TRUYEN = null;
		}
		
		private void attach_THINHHANHs(THINHHANH entity)
		{
			this.SendPropertyChanging();
			entity.TRUYEN = this;
		}
		
		private void detach_THINHHANHs(THINHHANH entity)
		{
			this.SendPropertyChanging();
			entity.TRUYEN = null;
		}
		
		private void attach_TruyenDangDocs(TruyenDangDoc entity)
		{
			this.SendPropertyChanging();
			entity.TRUYEN = this;
		}
		
		private void detach_TruyenDangDocs(TruyenDangDoc entity)
		{
			this.SendPropertyChanging();
			entity.TRUYEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CAMXUC")]
	public partial class CAMXUC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCX;
		
		private System.Nullable<int> _MaTruyen;
		
		private System.Nullable<int> _Tim;
		
		private System.Nullable<int> _Thich;
		
		private System.Nullable<int> _Haha;
		
		private System.Nullable<int> _Buon;
		
		private System.Nullable<int> _Gian;
		
		private EntityRef<TRUYEN> _TRUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCXChanging(int value);
    partial void OnMaCXChanged();
    partial void OnMaTruyenChanging(System.Nullable<int> value);
    partial void OnMaTruyenChanged();
    partial void OnTimChanging(System.Nullable<int> value);
    partial void OnTimChanged();
    partial void OnThichChanging(System.Nullable<int> value);
    partial void OnThichChanged();
    partial void OnHahaChanging(System.Nullable<int> value);
    partial void OnHahaChanged();
    partial void OnBuonChanging(System.Nullable<int> value);
    partial void OnBuonChanged();
    partial void OnGianChanging(System.Nullable<int> value);
    partial void OnGianChanged();
    #endregion
		
		public CAMXUC()
		{
			this._TRUYEN = default(EntityRef<TRUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCX", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCX
		{
			get
			{
				return this._MaCX;
			}
			set
			{
				if ((this._MaCX != value))
				{
					this.OnMaCXChanging(value);
					this.SendPropertyChanging();
					this._MaCX = value;
					this.SendPropertyChanged("MaCX");
					this.OnMaCXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTruyen", DbType="Int")]
		public System.Nullable<int> MaTruyen
		{
			get
			{
				return this._MaTruyen;
			}
			set
			{
				if ((this._MaTruyen != value))
				{
					if (this._TRUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTruyenChanging(value);
					this.SendPropertyChanging();
					this._MaTruyen = value;
					this.SendPropertyChanged("MaTruyen");
					this.OnMaTruyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tim", DbType="Int")]
		public System.Nullable<int> Tim
		{
			get
			{
				return this._Tim;
			}
			set
			{
				if ((this._Tim != value))
				{
					this.OnTimChanging(value);
					this.SendPropertyChanging();
					this._Tim = value;
					this.SendPropertyChanged("Tim");
					this.OnTimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thich", DbType="Int")]
		public System.Nullable<int> Thich
		{
			get
			{
				return this._Thich;
			}
			set
			{
				if ((this._Thich != value))
				{
					this.OnThichChanging(value);
					this.SendPropertyChanging();
					this._Thich = value;
					this.SendPropertyChanged("Thich");
					this.OnThichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Haha", DbType="Int")]
		public System.Nullable<int> Haha
		{
			get
			{
				return this._Haha;
			}
			set
			{
				if ((this._Haha != value))
				{
					this.OnHahaChanging(value);
					this.SendPropertyChanging();
					this._Haha = value;
					this.SendPropertyChanged("Haha");
					this.OnHahaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buon", DbType="Int")]
		public System.Nullable<int> Buon
		{
			get
			{
				return this._Buon;
			}
			set
			{
				if ((this._Buon != value))
				{
					this.OnBuonChanging(value);
					this.SendPropertyChanging();
					this._Buon = value;
					this.SendPropertyChanged("Buon");
					this.OnBuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gian", DbType="Int")]
		public System.Nullable<int> Gian
		{
			get
			{
				return this._Gian;
			}
			set
			{
				if ((this._Gian != value))
				{
					this.OnGianChanging(value);
					this.SendPropertyChanging();
					this._Gian = value;
					this.SendPropertyChanged("Gian");
					this.OnGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRUYEN_CAMXUC", Storage="_TRUYEN", ThisKey="MaTruyen", OtherKey="MaTruyen", IsForeignKey=true)]
		public TRUYEN TRUYEN
		{
			get
			{
				return this._TRUYEN.Entity;
			}
			set
			{
				TRUYEN previousValue = this._TRUYEN.Entity;
				if (((previousValue != value) 
							|| (this._TRUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRUYEN.Entity = null;
						previousValue.CAMXUCs.Remove(this);
					}
					this._TRUYEN.Entity = value;
					if ((value != null))
					{
						value.CAMXUCs.Add(this);
						this._MaTruyen = value.MaTruyen;
					}
					else
					{
						this._MaTruyen = default(Nullable<int>);
					}
					this.SendPropertyChanged("TRUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUONG")]
	public partial class CHUONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChuong;
		
		private int _MaTruyen;
		
		private int _IdChuong;
		
		private string _TenChuong;
		
		private System.Nullable<int> _MaDN;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private System.Nullable<int> _LuotXemChuong;
		
		private string _TenFoder;
		
		private EntityRef<TRUYEN> _TRUYEN;
		
		private EntityRef<DANGNHAP> _DANGNHAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChuongChanging(int value);
    partial void OnMaChuongChanged();
    partial void OnMaTruyenChanging(int value);
    partial void OnMaTruyenChanged();
    partial void OnIdChuongChanging(int value);
    partial void OnIdChuongChanged();
    partial void OnTenChuongChanging(string value);
    partial void OnTenChuongChanged();
    partial void OnMaDNChanging(System.Nullable<int> value);
    partial void OnMaDNChanged();
    partial void OnNgayDangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangChanged();
    partial void OnLuotXemChuongChanging(System.Nullable<int> value);
    partial void OnLuotXemChuongChanged();
    partial void OnTenFoderChanging(string value);
    partial void OnTenFoderChanged();
    #endregion
		
		public CHUONG()
		{
			this._TRUYEN = default(EntityRef<TRUYEN>);
			this._DANGNHAP = default(EntityRef<DANGNHAP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChuong
		{
			get
			{
				return this._MaChuong;
			}
			set
			{
				if ((this._MaChuong != value))
				{
					this.OnMaChuongChanging(value);
					this.SendPropertyChanging();
					this._MaChuong = value;
					this.SendPropertyChanged("MaChuong");
					this.OnMaChuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTruyen", DbType="Int NOT NULL")]
		public int MaTruyen
		{
			get
			{
				return this._MaTruyen;
			}
			set
			{
				if ((this._MaTruyen != value))
				{
					if (this._TRUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTruyenChanging(value);
					this.SendPropertyChanging();
					this._MaTruyen = value;
					this.SendPropertyChanged("MaTruyen");
					this.OnMaTruyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdChuong", DbType="Int NOT NULL")]
		public int IdChuong
		{
			get
			{
				return this._IdChuong;
			}
			set
			{
				if ((this._IdChuong != value))
				{
					this.OnIdChuongChanging(value);
					this.SendPropertyChanging();
					this._IdChuong = value;
					this.SendPropertyChanged("IdChuong");
					this.OnIdChuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChuong", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenChuong
		{
			get
			{
				return this._TenChuong;
			}
			set
			{
				if ((this._TenChuong != value))
				{
					this.OnTenChuongChanging(value);
					this.SendPropertyChanging();
					this._TenChuong = value;
					this.SendPropertyChanged("TenChuong");
					this.OnTenChuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDN", DbType="Int")]
		public System.Nullable<int> MaDN
		{
			get
			{
				return this._MaDN;
			}
			set
			{
				if ((this._MaDN != value))
				{
					if (this._DANGNHAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDNChanging(value);
					this.SendPropertyChanging();
					this._MaDN = value;
					this.SendPropertyChanged("MaDN");
					this.OnMaDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this.OnNgayDangChanging(value);
					this.SendPropertyChanging();
					this._NgayDang = value;
					this.SendPropertyChanged("NgayDang");
					this.OnNgayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotXemChuong", DbType="Int")]
		public System.Nullable<int> LuotXemChuong
		{
			get
			{
				return this._LuotXemChuong;
			}
			set
			{
				if ((this._LuotXemChuong != value))
				{
					this.OnLuotXemChuongChanging(value);
					this.SendPropertyChanging();
					this._LuotXemChuong = value;
					this.SendPropertyChanged("LuotXemChuong");
					this.OnLuotXemChuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenFoder", DbType="VarChar(50)")]
		public string TenFoder
		{
			get
			{
				return this._TenFoder;
			}
			set
			{
				if ((this._TenFoder != value))
				{
					this.OnTenFoderChanging(value);
					this.SendPropertyChanging();
					this._TenFoder = value;
					this.SendPropertyChanged("TenFoder");
					this.OnTenFoderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRUYEN_CHUONG", Storage="_TRUYEN", ThisKey="MaTruyen", OtherKey="MaTruyen", IsForeignKey=true)]
		public TRUYEN TRUYEN
		{
			get
			{
				return this._TRUYEN.Entity;
			}
			set
			{
				TRUYEN previousValue = this._TRUYEN.Entity;
				if (((previousValue != value) 
							|| (this._TRUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRUYEN.Entity = null;
						previousValue.CHUONGs.Remove(this);
					}
					this._TRUYEN.Entity = value;
					if ((value != null))
					{
						value.CHUONGs.Add(this);
						this._MaTruyen = value.MaTruyen;
					}
					else
					{
						this._MaTruyen = default(int);
					}
					this.SendPropertyChanged("TRUYEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANGNHAP_CHUONG", Storage="_DANGNHAP", ThisKey="MaDN", OtherKey="MaDN", IsForeignKey=true)]
		public DANGNHAP DANGNHAP
		{
			get
			{
				return this._DANGNHAP.Entity;
			}
			set
			{
				DANGNHAP previousValue = this._DANGNHAP.Entity;
				if (((previousValue != value) 
							|| (this._DANGNHAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANGNHAP.Entity = null;
						previousValue.CHUONGs.Remove(this);
					}
					this._DANGNHAP.Entity = value;
					if ((value != null))
					{
						value.CHUONGs.Add(this);
						this._MaDN = value.MaDN;
					}
					else
					{
						this._MaDN = default(Nullable<int>);
					}
					this.SendPropertyChanged("DANGNHAP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANGNHAP")]
	public partial class DANGNHAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDN;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _Email;
		
		private string _SDT;
		
		private string _avatar;
		
		private EntitySet<BinhLuan> _BinhLuans;
		
		private EntitySet<TRUYEN> _TRUYENs;
		
		private EntitySet<CHUONG> _CHUONGs;
		
		private EntitySet<Review> _Reviews;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDNChanging(int value);
    partial void OnMaDNChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnavatarChanging(string value);
    partial void OnavatarChanged();
    #endregion
		
		public DANGNHAP()
		{
			this._BinhLuans = new EntitySet<BinhLuan>(new Action<BinhLuan>(this.attach_BinhLuans), new Action<BinhLuan>(this.detach_BinhLuans));
			this._TRUYENs = new EntitySet<TRUYEN>(new Action<TRUYEN>(this.attach_TRUYENs), new Action<TRUYEN>(this.detach_TRUYENs));
			this._CHUONGs = new EntitySet<CHUONG>(new Action<CHUONG>(this.attach_CHUONGs), new Action<CHUONG>(this.detach_CHUONGs));
			this._Reviews = new EntitySet<Review>(new Action<Review>(this.attach_Reviews), new Action<Review>(this.detach_Reviews));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDN
		{
			get
			{
				return this._MaDN;
			}
			set
			{
				if ((this._MaDN != value))
				{
					this.OnMaDNChanging(value);
					this.SendPropertyChanging();
					this._MaDN = value;
					this.SendPropertyChanged("MaDN");
					this.OnMaDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string avatar
		{
			get
			{
				return this._avatar;
			}
			set
			{
				if ((this._avatar != value))
				{
					this.OnavatarChanging(value);
					this.SendPropertyChanging();
					this._avatar = value;
					this.SendPropertyChanged("avatar");
					this.OnavatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANGNHAP_BinhLuan", Storage="_BinhLuans", ThisKey="MaDN", OtherKey="MaDN")]
		public EntitySet<BinhLuan> BinhLuans
		{
			get
			{
				return this._BinhLuans;
			}
			set
			{
				this._BinhLuans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANGNHAP_TRUYEN", Storage="_TRUYENs", ThisKey="MaDN", OtherKey="MaDN")]
		public EntitySet<TRUYEN> TRUYENs
		{
			get
			{
				return this._TRUYENs;
			}
			set
			{
				this._TRUYENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANGNHAP_CHUONG", Storage="_CHUONGs", ThisKey="MaDN", OtherKey="MaDN")]
		public EntitySet<CHUONG> CHUONGs
		{
			get
			{
				return this._CHUONGs;
			}
			set
			{
				this._CHUONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANGNHAP_Review", Storage="_Reviews", ThisKey="MaDN", OtherKey="MaDN")]
		public EntitySet<Review> Reviews
		{
			get
			{
				return this._Reviews;
			}
			set
			{
				this._Reviews.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.DANGNHAP = this;
		}
		
		private void detach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.DANGNHAP = null;
		}
		
		private void attach_TRUYENs(TRUYEN entity)
		{
			this.SendPropertyChanging();
			entity.DANGNHAP = this;
		}
		
		private void detach_TRUYENs(TRUYEN entity)
		{
			this.SendPropertyChanging();
			entity.DANGNHAP = null;
		}
		
		private void attach_CHUONGs(CHUONG entity)
		{
			this.SendPropertyChanging();
			entity.DANGNHAP = this;
		}
		
		private void detach_CHUONGs(CHUONG entity)
		{
			this.SendPropertyChanging();
			entity.DANGNHAP = null;
		}
		
		private void attach_Reviews(Review entity)
		{
			this.SendPropertyChanging();
			entity.DANGNHAP = this;
		}
		
		private void detach_Reviews(Review entity)
		{
			this.SendPropertyChanging();
			entity.DANGNHAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DECU")]
	public partial class DECU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDC;
		
		private System.Nullable<int> _MaTruyen;
		
		private System.Nullable<int> _DiemDeCu;
		
		private EntityRef<TRUYEN> _TRUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDCChanging(int value);
    partial void OnMaDCChanged();
    partial void OnMaTruyenChanging(System.Nullable<int> value);
    partial void OnMaTruyenChanged();
    partial void OnDiemDeCuChanging(System.Nullable<int> value);
    partial void OnDiemDeCuChanged();
    #endregion
		
		public DECU()
		{
			this._TRUYEN = default(EntityRef<TRUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDC
		{
			get
			{
				return this._MaDC;
			}
			set
			{
				if ((this._MaDC != value))
				{
					this.OnMaDCChanging(value);
					this.SendPropertyChanging();
					this._MaDC = value;
					this.SendPropertyChanged("MaDC");
					this.OnMaDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTruyen", DbType="Int")]
		public System.Nullable<int> MaTruyen
		{
			get
			{
				return this._MaTruyen;
			}
			set
			{
				if ((this._MaTruyen != value))
				{
					if (this._TRUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTruyenChanging(value);
					this.SendPropertyChanging();
					this._MaTruyen = value;
					this.SendPropertyChanged("MaTruyen");
					this.OnMaTruyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemDeCu", DbType="Int")]
		public System.Nullable<int> DiemDeCu
		{
			get
			{
				return this._DiemDeCu;
			}
			set
			{
				if ((this._DiemDeCu != value))
				{
					this.OnDiemDeCuChanging(value);
					this.SendPropertyChanging();
					this._DiemDeCu = value;
					this.SendPropertyChanged("DiemDeCu");
					this.OnDiemDeCuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRUYEN_DECU", Storage="_TRUYEN", ThisKey="MaTruyen", OtherKey="MaTruyen", IsForeignKey=true)]
		public TRUYEN TRUYEN
		{
			get
			{
				return this._TRUYEN.Entity;
			}
			set
			{
				TRUYEN previousValue = this._TRUYEN.Entity;
				if (((previousValue != value) 
							|| (this._TRUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRUYEN.Entity = null;
						previousValue.DECUs.Remove(this);
					}
					this._TRUYEN.Entity = value;
					if ((value != null))
					{
						value.DECUs.Add(this);
						this._MaTruyen = value.MaTruyen;
					}
					else
					{
						this._MaTruyen = default(Nullable<int>);
					}
					this.SendPropertyChanged("TRUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANTHUONG")]
	public partial class NHANTHUONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNT;
		
		private System.Nullable<int> _MaTruyen;
		
		private System.Nullable<int> _DiemNT;
		
		private EntityRef<TRUYEN> _TRUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNTChanging(int value);
    partial void OnMaNTChanged();
    partial void OnMaTruyenChanging(System.Nullable<int> value);
    partial void OnMaTruyenChanged();
    partial void OnDiemNTChanging(System.Nullable<int> value);
    partial void OnDiemNTChanged();
    #endregion
		
		public NHANTHUONG()
		{
			this._TRUYEN = default(EntityRef<TRUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNT
		{
			get
			{
				return this._MaNT;
			}
			set
			{
				if ((this._MaNT != value))
				{
					this.OnMaNTChanging(value);
					this.SendPropertyChanging();
					this._MaNT = value;
					this.SendPropertyChanged("MaNT");
					this.OnMaNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTruyen", DbType="Int")]
		public System.Nullable<int> MaTruyen
		{
			get
			{
				return this._MaTruyen;
			}
			set
			{
				if ((this._MaTruyen != value))
				{
					if (this._TRUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTruyenChanging(value);
					this.SendPropertyChanging();
					this._MaTruyen = value;
					this.SendPropertyChanged("MaTruyen");
					this.OnMaTruyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemNT", DbType="Int")]
		public System.Nullable<int> DiemNT
		{
			get
			{
				return this._DiemNT;
			}
			set
			{
				if ((this._DiemNT != value))
				{
					this.OnDiemNTChanging(value);
					this.SendPropertyChanging();
					this._DiemNT = value;
					this.SendPropertyChanged("DiemNT");
					this.OnDiemNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRUYEN_NHANTHUONG", Storage="_TRUYEN", ThisKey="MaTruyen", OtherKey="MaTruyen", IsForeignKey=true)]
		public TRUYEN TRUYEN
		{
			get
			{
				return this._TRUYEN.Entity;
			}
			set
			{
				TRUYEN previousValue = this._TRUYEN.Entity;
				if (((previousValue != value) 
							|| (this._TRUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRUYEN.Entity = null;
						previousValue.NHANTHUONGs.Remove(this);
					}
					this._TRUYEN.Entity = value;
					if ((value != null))
					{
						value.NHANTHUONGs.Add(this);
						this._MaTruyen = value.MaTruyen;
					}
					else
					{
						this._MaTruyen = default(Nullable<int>);
					}
					this.SendPropertyChanged("TRUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rank_DeCu")]
	public partial class Rank_DeCu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNT;
		
		private System.Nullable<int> _MaTruyen;
		
		private System.Nullable<int> _DiemDC;
		
		private EntityRef<TRUYEN> _TRUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNTChanging(int value);
    partial void OnMaNTChanged();
    partial void OnMaTruyenChanging(System.Nullable<int> value);
    partial void OnMaTruyenChanged();
    partial void OnDiemDCChanging(System.Nullable<int> value);
    partial void OnDiemDCChanged();
    #endregion
		
		public Rank_DeCu()
		{
			this._TRUYEN = default(EntityRef<TRUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNT
		{
			get
			{
				return this._MaNT;
			}
			set
			{
				if ((this._MaNT != value))
				{
					this.OnMaNTChanging(value);
					this.SendPropertyChanging();
					this._MaNT = value;
					this.SendPropertyChanged("MaNT");
					this.OnMaNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTruyen", DbType="Int")]
		public System.Nullable<int> MaTruyen
		{
			get
			{
				return this._MaTruyen;
			}
			set
			{
				if ((this._MaTruyen != value))
				{
					if (this._TRUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTruyenChanging(value);
					this.SendPropertyChanging();
					this._MaTruyen = value;
					this.SendPropertyChanged("MaTruyen");
					this.OnMaTruyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemDC", DbType="Int")]
		public System.Nullable<int> DiemDC
		{
			get
			{
				return this._DiemDC;
			}
			set
			{
				if ((this._DiemDC != value))
				{
					this.OnDiemDCChanging(value);
					this.SendPropertyChanging();
					this._DiemDC = value;
					this.SendPropertyChanged("DiemDC");
					this.OnDiemDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRUYEN_Rank_DeCu", Storage="_TRUYEN", ThisKey="MaTruyen", OtherKey="MaTruyen", IsForeignKey=true)]
		public TRUYEN TRUYEN
		{
			get
			{
				return this._TRUYEN.Entity;
			}
			set
			{
				TRUYEN previousValue = this._TRUYEN.Entity;
				if (((previousValue != value) 
							|| (this._TRUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRUYEN.Entity = null;
						previousValue.Rank_DeCus.Remove(this);
					}
					this._TRUYEN.Entity = value;
					if ((value != null))
					{
						value.Rank_DeCus.Add(this);
						this._MaTruyen = value.MaTruyen;
					}
					else
					{
						this._MaTruyen = default(Nullable<int>);
					}
					this.SendPropertyChanged("TRUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Review")]
	public partial class Review : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaRV;
		
		private System.Nullable<int> _MaTruyen;
		
		private System.Nullable<int> _MaDN;
		
		private string _NoiDung;
		
		private System.Nullable<int> _TinhCachNhanVat;
		
		private System.Nullable<int> _CotTruyen;
		
		private System.Nullable<int> _BoCucTheGioi;
		
		private EntityRef<DANGNHAP> _DANGNHAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaRVChanging(int value);
    partial void OnMaRVChanged();
    partial void OnMaTruyenChanging(System.Nullable<int> value);
    partial void OnMaTruyenChanged();
    partial void OnMaDNChanging(System.Nullable<int> value);
    partial void OnMaDNChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnTinhCachNhanVatChanging(System.Nullable<int> value);
    partial void OnTinhCachNhanVatChanged();
    partial void OnCotTruyenChanging(System.Nullable<int> value);
    partial void OnCotTruyenChanged();
    partial void OnBoCucTheGioiChanging(System.Nullable<int> value);
    partial void OnBoCucTheGioiChanged();
    #endregion
		
		public Review()
		{
			this._DANGNHAP = default(EntityRef<DANGNHAP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaRV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaRV
		{
			get
			{
				return this._MaRV;
			}
			set
			{
				if ((this._MaRV != value))
				{
					this.OnMaRVChanging(value);
					this.SendPropertyChanging();
					this._MaRV = value;
					this.SendPropertyChanged("MaRV");
					this.OnMaRVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTruyen", DbType="Int")]
		public System.Nullable<int> MaTruyen
		{
			get
			{
				return this._MaTruyen;
			}
			set
			{
				if ((this._MaTruyen != value))
				{
					this.OnMaTruyenChanging(value);
					this.SendPropertyChanging();
					this._MaTruyen = value;
					this.SendPropertyChanged("MaTruyen");
					this.OnMaTruyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDN", DbType="Int")]
		public System.Nullable<int> MaDN
		{
			get
			{
				return this._MaDN;
			}
			set
			{
				if ((this._MaDN != value))
				{
					if (this._DANGNHAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDNChanging(value);
					this.SendPropertyChanging();
					this._MaDN = value;
					this.SendPropertyChanged("MaDN");
					this.OnMaDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(500)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhCachNhanVat", DbType="Int")]
		public System.Nullable<int> TinhCachNhanVat
		{
			get
			{
				return this._TinhCachNhanVat;
			}
			set
			{
				if ((this._TinhCachNhanVat != value))
				{
					this.OnTinhCachNhanVatChanging(value);
					this.SendPropertyChanging();
					this._TinhCachNhanVat = value;
					this.SendPropertyChanged("TinhCachNhanVat");
					this.OnTinhCachNhanVatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CotTruyen", DbType="Int")]
		public System.Nullable<int> CotTruyen
		{
			get
			{
				return this._CotTruyen;
			}
			set
			{
				if ((this._CotTruyen != value))
				{
					this.OnCotTruyenChanging(value);
					this.SendPropertyChanging();
					this._CotTruyen = value;
					this.SendPropertyChanged("CotTruyen");
					this.OnCotTruyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoCucTheGioi", DbType="Int")]
		public System.Nullable<int> BoCucTheGioi
		{
			get
			{
				return this._BoCucTheGioi;
			}
			set
			{
				if ((this._BoCucTheGioi != value))
				{
					this.OnBoCucTheGioiChanging(value);
					this.SendPropertyChanging();
					this._BoCucTheGioi = value;
					this.SendPropertyChanged("BoCucTheGioi");
					this.OnBoCucTheGioiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANGNHAP_Review", Storage="_DANGNHAP", ThisKey="MaDN", OtherKey="MaDN", IsForeignKey=true)]
		public DANGNHAP DANGNHAP
		{
			get
			{
				return this._DANGNHAP.Entity;
			}
			set
			{
				DANGNHAP previousValue = this._DANGNHAP.Entity;
				if (((previousValue != value) 
							|| (this._DANGNHAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANGNHAP.Entity = null;
						previousValue.Reviews.Remove(this);
					}
					this._DANGNHAP.Entity = value;
					if ((value != null))
					{
						value.Reviews.Add(this);
						this._MaDN = value.MaDN;
					}
					else
					{
						this._MaDN = default(Nullable<int>);
					}
					this.SendPropertyChanged("DANGNHAP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TACGIA")]
	public partial class TACGIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTG;
		
		private string _TenTG;
		
		private string _DiaChi;
		
		private string _TieuSu;
		
		private EntitySet<TRUYEN> _TRUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTGChanging(string value);
    partial void OnMaTGChanged();
    partial void OnTenTGChanging(string value);
    partial void OnTenTGChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnTieuSuChanging(string value);
    partial void OnTieuSuChanged();
    #endregion
		
		public TACGIA()
		{
			this._TRUYENs = new EntitySet<TRUYEN>(new Action<TRUYEN>(this.attach_TRUYENs), new Action<TRUYEN>(this.detach_TRUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					this.OnMaTGChanging(value);
					this.SendPropertyChanging();
					this._MaTG = value;
					this.SendPropertyChanged("MaTG");
					this.OnMaTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTG", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenTG
		{
			get
			{
				return this._TenTG;
			}
			set
			{
				if ((this._TenTG != value))
				{
					this.OnTenTGChanging(value);
					this.SendPropertyChanging();
					this._TenTG = value;
					this.SendPropertyChanged("TenTG");
					this.OnTenTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuSu", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TieuSu
		{
			get
			{
				return this._TieuSu;
			}
			set
			{
				if ((this._TieuSu != value))
				{
					this.OnTieuSuChanging(value);
					this.SendPropertyChanging();
					this._TieuSu = value;
					this.SendPropertyChanged("TieuSu");
					this.OnTieuSuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TACGIA_TRUYEN", Storage="_TRUYENs", ThisKey="MaTG", OtherKey="MaTG")]
		public EntitySet<TRUYEN> TRUYENs
		{
			get
			{
				return this._TRUYENs;
			}
			set
			{
				this._TRUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TRUYENs(TRUYEN entity)
		{
			this.SendPropertyChanging();
			entity.TACGIA = this;
		}
		
		private void detach_TRUYENs(TRUYEN entity)
		{
			this.SendPropertyChanging();
			entity.TACGIA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THELOAI")]
	public partial class THELOAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTL;
		
		private string _TenTL;
		
		private EntitySet<TRUYEN> _TRUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTLChanging(string value);
    partial void OnMaTLChanged();
    partial void OnTenTLChanging(string value);
    partial void OnTenTLChanged();
    #endregion
		
		public THELOAI()
		{
			this._TRUYENs = new EntitySet<TRUYEN>(new Action<TRUYEN>(this.attach_TRUYENs), new Action<TRUYEN>(this.detach_TRUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTL", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTL
		{
			get
			{
				return this._MaTL;
			}
			set
			{
				if ((this._MaTL != value))
				{
					this.OnMaTLChanging(value);
					this.SendPropertyChanging();
					this._MaTL = value;
					this.SendPropertyChanged("MaTL");
					this.OnMaTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTL", DbType="NVarChar(50)")]
		public string TenTL
		{
			get
			{
				return this._TenTL;
			}
			set
			{
				if ((this._TenTL != value))
				{
					this.OnTenTLChanging(value);
					this.SendPropertyChanging();
					this._TenTL = value;
					this.SendPropertyChanged("TenTL");
					this.OnTenTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THELOAI_TRUYEN", Storage="_TRUYENs", ThisKey="MaTL", OtherKey="MaTL")]
		public EntitySet<TRUYEN> TRUYENs
		{
			get
			{
				return this._TRUYENs;
			}
			set
			{
				this._TRUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TRUYENs(TRUYEN entity)
		{
			this.SendPropertyChanging();
			entity.THELOAI = this;
		}
		
		private void detach_TRUYENs(TRUYEN entity)
		{
			this.SendPropertyChanging();
			entity.THELOAI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THINHHANH")]
	public partial class THINHHANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTH;
		
		private System.Nullable<int> _MaTruyen;
		
		private System.Nullable<int> _DiemTH;
		
		private EntityRef<TRUYEN> _TRUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTHChanging(int value);
    partial void OnMaTHChanged();
    partial void OnMaTruyenChanging(System.Nullable<int> value);
    partial void OnMaTruyenChanged();
    partial void OnDiemTHChanging(System.Nullable<int> value);
    partial void OnDiemTHChanged();
    #endregion
		
		public THINHHANH()
		{
			this._TRUYEN = default(EntityRef<TRUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTH
		{
			get
			{
				return this._MaTH;
			}
			set
			{
				if ((this._MaTH != value))
				{
					this.OnMaTHChanging(value);
					this.SendPropertyChanging();
					this._MaTH = value;
					this.SendPropertyChanged("MaTH");
					this.OnMaTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTruyen", DbType="Int")]
		public System.Nullable<int> MaTruyen
		{
			get
			{
				return this._MaTruyen;
			}
			set
			{
				if ((this._MaTruyen != value))
				{
					if (this._TRUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTruyenChanging(value);
					this.SendPropertyChanging();
					this._MaTruyen = value;
					this.SendPropertyChanged("MaTruyen");
					this.OnMaTruyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemTH", DbType="Int")]
		public System.Nullable<int> DiemTH
		{
			get
			{
				return this._DiemTH;
			}
			set
			{
				if ((this._DiemTH != value))
				{
					this.OnDiemTHChanging(value);
					this.SendPropertyChanging();
					this._DiemTH = value;
					this.SendPropertyChanged("DiemTH");
					this.OnDiemTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRUYEN_THINHHANH", Storage="_TRUYEN", ThisKey="MaTruyen", OtherKey="MaTruyen", IsForeignKey=true)]
		public TRUYEN TRUYEN
		{
			get
			{
				return this._TRUYEN.Entity;
			}
			set
			{
				TRUYEN previousValue = this._TRUYEN.Entity;
				if (((previousValue != value) 
							|| (this._TRUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRUYEN.Entity = null;
						previousValue.THINHHANHs.Remove(this);
					}
					this._TRUYEN.Entity = value;
					if ((value != null))
					{
						value.THINHHANHs.Add(this);
						this._MaTruyen = value.MaTruyen;
					}
					else
					{
						this._MaTruyen = default(Nullable<int>);
					}
					this.SendPropertyChanged("TRUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TruyenDangDoc")]
	public partial class TruyenDangDoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATDC;
		
		private System.Nullable<int> _MaTruyen;
		
		private System.Nullable<int> _IdChuong;
		
		private EntityRef<TRUYEN> _TRUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATDCChanging(int value);
    partial void OnMATDCChanged();
    partial void OnMaTruyenChanging(System.Nullable<int> value);
    partial void OnMaTruyenChanged();
    partial void OnIdChuongChanging(System.Nullable<int> value);
    partial void OnIdChuongChanged();
    #endregion
		
		public TruyenDangDoc()
		{
			this._TRUYEN = default(EntityRef<TRUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATDC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MATDC
		{
			get
			{
				return this._MATDC;
			}
			set
			{
				if ((this._MATDC != value))
				{
					this.OnMATDCChanging(value);
					this.SendPropertyChanging();
					this._MATDC = value;
					this.SendPropertyChanged("MATDC");
					this.OnMATDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTruyen", DbType="Int")]
		public System.Nullable<int> MaTruyen
		{
			get
			{
				return this._MaTruyen;
			}
			set
			{
				if ((this._MaTruyen != value))
				{
					if (this._TRUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTruyenChanging(value);
					this.SendPropertyChanging();
					this._MaTruyen = value;
					this.SendPropertyChanged("MaTruyen");
					this.OnMaTruyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdChuong", DbType="Int")]
		public System.Nullable<int> IdChuong
		{
			get
			{
				return this._IdChuong;
			}
			set
			{
				if ((this._IdChuong != value))
				{
					this.OnIdChuongChanging(value);
					this.SendPropertyChanging();
					this._IdChuong = value;
					this.SendPropertyChanged("IdChuong");
					this.OnIdChuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRUYEN_TruyenDangDoc", Storage="_TRUYEN", ThisKey="MaTruyen", OtherKey="MaTruyen", IsForeignKey=true)]
		public TRUYEN TRUYEN
		{
			get
			{
				return this._TRUYEN.Entity;
			}
			set
			{
				TRUYEN previousValue = this._TRUYEN.Entity;
				if (((previousValue != value) 
							|| (this._TRUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRUYEN.Entity = null;
						previousValue.TruyenDangDocs.Remove(this);
					}
					this._TRUYEN.Entity = value;
					if ((value != null))
					{
						value.TruyenDangDocs.Add(this);
						this._MaTruyen = value.MaTruyen;
					}
					else
					{
						this._MaTruyen = default(Nullable<int>);
					}
					this.SendPropertyChanged("TRUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
